name: Build and Push to GHCR

on:
  push:
    branches: ["master"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: $${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20" # Matches your @types/node version
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

  build-and-push:
    needs: unit-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This stores your Docker layers so builds take seconds instead of minutes
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set lower case repo name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=short
            type=ref,event=branch
            latest

      # --- The Build Step ---
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # These two lines save you build minutes by reusing old layers
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          # We create a temporary inventory in-line
          inventory: |
            [vps]
            ${{ secrets.VPS_HOST }} ansible_port=${{ secrets.VPS_SSH_PORT }} ansible_user=${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          options: |
            --extra-vars "ansible_ssh_extra_args='-o StrictHostKeyChecking=no'"
